services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8005:8000"  # Changed from 8000:8000 to 8005:8000
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_SERVER_URL=http://chromadb:8000  # Internal Docker network still uses port 8000
      - COLLECTION_NAME=kb_default
      - EMBED_MODEL_NAME=text-embedding-3-small
      - MODEL_NAME=gpt-3.5-turbo
      - WHATSAPP_TOKEN=your_whatsapp_verify_token
      - WHATSAPP_APP_SECRET=your_app_secret
      - WHATSAPP_PHONE_ID=your_phone_number_id
      - WHATSAPP_VERSION=v17.0
      - EXPOSE_CONFIDENCE_SCORE=true
      - INCLUDE_CONFIDENCE_REASON=true
      - ENABLE_DATABASE_STORAGE=${ENABLE_DATABASE_STORAGE:-true}
      - CONFIDENCE_THRESHOLD=70.0
    depends_on:
      - chromadb
    volumes:
    - ./data:/app/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend