services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8005:8000"  # Changed from 8000:8000 to 8005:8000
    environment:
      - CHROMA_DB_IMPL=postgres
      - CHROMA_POSTGRES_USER=${PGUSER}
      - CHROMA_POSTGRES_PASSWORD=${PGPASSWORD}
      - CHROMA_POSTGRES_DB=${PGDATABASE}
      - CHROMA_POSTGRES_HOST=${PGHOST}
      - CHROMA_POSTGRES_PORT=${PGPORT}
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_SERVER_URL=http://chromadb:8000  # Internal Docker network still uses port 8000
      - COLLECTION_NAME=kb_default
      - EMBED_MODEL_NAME=text-embedding-ada-002
      - MODEL_NAME=gpt-3.5-turbo
    volumes:
      - ./kb_files:/app/kb_files
    depends_on:
      - chromadb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  chroma_data:
    name: chroma_data
    external: true  # Mark as external to use existing volume